package cn.edu.ecnu.dao;

import cn.edu.ecnu.domain.JudgeTeacherProject;
import cn.edu.ecnu.domain.JudgeTeacherProjectExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface JudgeTeacherProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge_teacher_project
     *
     * @mbggenerated
     */
    int countByExample(JudgeTeacherProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge_teacher_project
     *
     * @mbggenerated
     */
    int deleteByExample(JudgeTeacherProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge_teacher_project
     *
     * @mbggenerated
     */
    int insert(JudgeTeacherProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge_teacher_project
     *
     * @mbggenerated
     */
    int insertSelective(JudgeTeacherProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge_teacher_project
     *
     * @mbggenerated
     */
    List<JudgeTeacherProject> selectByExample(JudgeTeacherProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge_teacher_project
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") JudgeTeacherProject record, @Param("example") JudgeTeacherProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge_teacher_project
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") JudgeTeacherProject record, @Param("example") JudgeTeacherProjectExample example);
}