package cn.edu.ecnu.dao;

import cn.edu.ecnu.domain.TeamStudent;
import cn.edu.ecnu.domain.TeamStudentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TeamStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_student
     *
     * @mbggenerated
     */
    int countByExample(TeamStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_student
     *
     * @mbggenerated
     */
    int deleteByExample(TeamStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_student
     *
     * @mbggenerated
     */
    int insert(TeamStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_student
     *
     * @mbggenerated
     */
    int insertSelective(TeamStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_student
     *
     * @mbggenerated
     */
    List<TeamStudent> selectByExample(TeamStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_student
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TeamStudent record, @Param("example") TeamStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_student
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TeamStudent record, @Param("example") TeamStudentExample example);
}