package cn.edu.ecnu.domain;

import java.io.Serializable;

public class JudgeTeacherProject implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judge_teacher_project.tid
     *
     * @mbggenerated
     */
    private String tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judge_teacher_project.pid
     *
     * @mbggenerated
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table judge_teacher_project
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judge_teacher_project.tid
     *
     * @return the value of judge_teacher_project.tid
     *
     * @mbggenerated
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judge_teacher_project.tid
     *
     * @param tid the value for judge_teacher_project.tid
     *
     * @mbggenerated
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judge_teacher_project.pid
     *
     * @return the value of judge_teacher_project.pid
     *
     * @mbggenerated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judge_teacher_project.pid
     *
     * @param pid the value for judge_teacher_project.pid
     *
     * @mbggenerated
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge_teacher_project
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tid=").append(tid);
        sb.append(", pid=").append(pid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}